version: "3.8"

services:
  williams-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: williams-portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
      - NEXT_PUBLIC_RECAPTCHA_SECRET_KEY=${NEXT_PUBLIC_RECAPTCHA_SECRET_KEY}
      - NEXT_PUBLIC_EMAIL_ADDRESS=${NEXT_PUBLIC_EMAIL_ADDRESS}
      - NEXT_PUBLIC_EMAIL_PASSWORD=${NEXT_PUBLIC_EMAIL_PASSWORD}
      - NEXT_PUBLIC_EMAIL_SERVICE=${NEXT_PUBLIC_EMAIL_SERVICE}
      - NEXT_PUBLIC_EMAIL_PORT=${NEXT_PUBLIC_EMAIL_PORT}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - williams-network

networks:
  williams-network:
    driver: bridge
