version: "3.8"

services:
  williams-portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: williams-portfolio-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - williams-dev-network

networks:
  williams-dev-network:
    driver: bridge
